-- phpMyAdmin SQL Dump
-- version 4.2.7.1
-- http://www.phpmyadmin.net
--
-- Client :  127.0.0.1
-- Généré le :  Sam 06 Décembre 2014 à 22:32
-- Version du serveur :  5.6.20
-- Version de PHP :  5.5.15

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `agnamstore`
--

-- --------------------------------------------------------

--
-- Structure de la table `item`
--

CREATE TABLE IF NOT EXISTS `item` (
`item_id` int(11) NOT NULL,
  `price` decimal(21,2) NOT NULL,
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `sale_date` date NOT NULL,
  `year` int(4) NOT NULL,
  `author` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8_unicode_ci,
  `image` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `item_type_id` int(11) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=47 ;

--
-- Contenu de la table `item`
--

INSERT INTO `item` (`item_id`, `price`, `name`, `sale_date`, `year`, `author`, `description`, `image`, `item_type_id`) VALUES
(1, '19.99', 'Hunter X Hunter', '0000-00-00', 2011, 'Yoshihiro Togashi', 'Réadaptation du célèbre manga Hunter x Hunter en une nouvelle série.\r\n\r\nLe jeune Gon vit sur une petite île avec sa tante. Abandonné par son père qui est un Hunter, à la fois un aventurier et un chasseur de primes, Gon décide à l''âge de 12 ans de partir pour devenir un Hunter.\r\nCela ne sera pas chose aisée, il devra passer une suite de tests et examens en compagnie de milliers d''autres prétendants au titre de Hunter.\r\nIl sera aidé par de nouvelles connaissances qui aspirent au même but que lui tel que Kurapika, Leolio et Kirua. ', 'a_img_hxh.png', 2),
(2, '19.99', 'Fairy Tail', '0000-00-00', 2011, 'Hiro Mashima', 'Lucy est une jeune magicienne qui désire plus que tout entrer dans une guilde magique.\r\nElle décide de se rendre à Harujion afin d''obtenir des infos sur des guildes, particulièrement la guilde Fairy Tail.\r\n\r\nLors de ses recherches, elle rencontre le mystérieux Salamander membre de la célèbre Guilde Fairy Tail.\r\nMalheureusement ce dernier n''est qu''un charlatan qui utilise des enchantements pour envoûter des femmes pour ensuite les revendre au marché des esclaves !\r\n\r\nAlors que Lucy se trouve sous l''envoûtement de Salamander, un garçon mystérieux du nom de Natsu accompagné d''un chat bleu pouvant parler appelé Happy, la percute et rompt le sortilège de Salamander. Pour remercier Natsu et Happy elle décide de les invités au restaurant. Plus tard, Salamander lui fit une proposition " Si elle viens à la fête sur le bateau (organisé par Salamander) il la ferait entrer a Fairy Tail". Lucy accepte et s''y rend. A la fête elle se rend compte que Salamander n''est qu''un escroc et qu''il ne fait même pas partie de Fairy Tail, elle veut fuir mais elle est sur le point de se faire kidnapper lorsque Natsu et Happy arrive et sauve Lucy, c''est alors quel découvre qu''ils sont des mages et qu''ils font partie de Fairy Tail.\r\n\r\nC''est le début des aventures de Natsu et Lucy au sein du monde magique de Fairy Tail !', 'a_img_ft.png', 2),
(3, '19.99', 'Naruto', '0000-00-00', 2011, 'blabla', 'Dans le village de Konoha vie Naruto, un jeune garçon détesté et craint des villageois. Il est craint du faite qu''il détient en lui Kyuubi (démon renard à neuf queues) d''une incroyable force, qui a tué un grand nombre de personnes. Le ninja le plus puissant de Konoha à l''époque, le quatrième Hokage, Yondaime réussit à sceller ce démon dans le corps de Naruto.\r\nMalheureusement il y laissa la vie.\r\n\r\nC''est ainsi que douze ans plus tard, Naruto rêve de devenir le plus grand Hokage de Konoha afin que tous le reconnaissent. Mais la route pour devenir Hokage est très longue et Naruto doit remplir un bon nombre d''épreuves et affronter de nombreux ennemis pour atteindre son but !', 'a_img_naruto.png', 2),
(4, '19.99', 'Elfen Lied', '0000-00-00', 2002, 'Lynn Okamoto', 'Lucy, une diclonius (génération spontanée de mutants annonçant un événement), est gardée dans un laboratoire de haute sécurité dans lequel des expériences sont réalisées sur ces êtres surhumains. Suite à un accident, elle parvient à s''échapper en tuant sauvagement toute personne entravant son chemin, grâce à ses "main" (ce sont des "mains" extrêmement tranchantes, personne ne les voient). Une fois à l''extérieur du bâtiment, un garde sniper réussit à la toucher en pleine tête et la fait tomber dans la mer.\r\n\r\nLe lendemain, Kouta un jeune garçon qui revient dans la ville où il est né, Kamakura, donne un rendez-vous à sa cousine Yuka qu''il n''a pas vu depuis son accident : depuis son enfance. Ils décident alors d''aller à la plage, où ils jouaient quand ils étaient enfants avec la petite soeur de Kouta, Kanae, qui est morte d''une grave maladie. Là-bas, ils rencontrent une jeune fille mystérieuse qui, apparemment, a perdu la mémoire. Sans savoir où elle habite, Kouta et Yuka l''emmènent chez eux et lui donne un nom : Nyu, c''est le seul mot qu''elle arrive a prononcer !\r\n\r\nMais suite à l''évasion qui s''est produite au laboratoire, l''Unité d''Assaut Spécial (S.A.T.) a reçu le feu vert pour éliminer la fugitive, Lucy qui se révèle en réalité être la mystérieuse Nyu...', 'a_img_elfen.png', 2),
(5, '19.99', 'Gantz', '0000-00-00', 2000, 'Hiroya Oku', 'Tout se passe dans une station de métro, Kei Kurono, un étudiant typique qui ne se préoccupe que de lui-même, attend tranquillement le métro pour rentre chez lui. Soudain, un clochard ayant un peu trop bu s''évanouit et tombe sur les rails. Personne ne vient lui porter secours mis à part Masaru Katô, un ami d''enfance de Kei. Il demande à Kei de l''aider mais quand ils réussissent à remonter le clochard, il est trop tard. Le métro arrive et ne leur laisse pas le temps de regagner le quai. Ils sont écrasés. Quelques secondes plus tard, ils se retrouvent téléportés dans un appartement fermé en compagnie de d''autres personnes récemment tuées. A partir de maintenant leur vie va être contrôlée par une mystérieuse boule noire appelée GANTZ et seront forcés de participer à un "jeu" de danger et d''horreur sans précédent.', 'a_img_gantz.png', 2),
(6, '19.99', 'School Rumble', '0000-00-00', 2003, 'Jin Kobayashi', 'Tenma Tsukamoto, une lycéenne un peu idiote, est folle amoureuse de Ouji Karasuma, un garçon de son lycée. Elle se retrouve dans la même classe que lui et espère bien pouvoir lui déclarer sa flamme. Parallèlement à cela, Kenji Harima un lycéen voyou très bagarreur est lui amoureux de Tsukamoto, mais ne sait pas comment lui avouer ses sentiments.\r\nCes trois-là se retrouvent dans la même classe. Tsukamoto et Harima vont tout faire pour\r\nséduire l''élu de leur coeur et il va en découler une vraie série de gags.', 'a_img_rumble.png', 2),
(7, '19.99', 'GTO', '0000-00-00', 1997, 'Toru Fujisawa', 'Ancien voyou, chef de gang, Eikichi Onizuka décide un jour de devenir prof. Sa vocation n''a rien de pédagogique. Ce qu''il veut, c''est pouvoir sortir avec les étudiantes du lycée où il travaille. Pourtant, au fil des chapitres, on se rend compte que le sens de la justice et de l''honneur de notre héros vont l''amener à devenir un véritable enseignant.\r\nCette série de Tôru Fujisawa a connu un tel succès au Japon qu''elle fut adaptée en feuilleton " live " à la télé et au cinéma. Drôle et " vrai ", plein de rebondissements et doté d''une psychologie rare dans ce domaine, GTO met en scène des adolescents en quête d''identité comme il en existe partout.', 'a_img_gto.png', 2),
(8, '19.99', 'Hikaru No Go', '0000-00-00', 1998, 'Yumi Hotta', 'Le jeune Hikaru découvre un jour dans le grenier de son grand-père un goban (plateau de jeu de go). L''objet se révèle hanté par un fantôme nommé Saï, ancien professeur de go de l''empereur sous l''ère Heian. Saï se retrouve piégé dans l''esprit de Hikaru et lui donne peu à peu le goût du go. Se laissant guider dans ses débuts par Saï, Hikaru rencontre et vainc Akira, un jeune prodige. Dès lors, les deux jeunes garçons ne vont cesser de progresser et de se poursuivre.\r\n\r\nCette série réussit la gageure d''introduire de manière ludique et souvent dramatique certains aspects du jeu de go et de son éthique au sein d''un Shōnen manga, alors que le sujet ne semblait guère s''y prêter à priori. Le succès du manga comme de l''anime a d''ailleurs suscité un net regain d''intérêt pour le go chez les jeunes Japonais, puis dans le reste du monde suivant la diffusion de la série.', 'a_img_hikaru.png', 2),
(9, '19.99', 'Zipang', '0000-00-00', 2000, '', 'Le Mirai, bâtiment de la marine japonaise fait route vers l''Amérique du Sud pour une mission de soutien quand il est soudainement pris dans un orage magnétique. \r\n\r\nDès que le beau temps revient, le Yamato, célèbre navire japonais datant de la Guerre du Pacifique est en vue. De plus, les hommes sur le pont constatent que la lune n''est plus au même quartier... C''est impossible, mais le Mirai semble avoir remonté le cours du temps, juste après l''attaque de Pearl Harbor ! \r\n\r\nUn croiseur japonais doté du meilleur armement du 21ème siècle se retrouve en pleine 2nde guerre mondiale, doit-il rester neutre ou prendre part au conflit et si tel était le cas, quelles en seraient les conséquences ? C''est cette question qui revient sans cesse et qui tiraille les membres de l''équipage.', 'a_img_zipang.png', 2),
(10, '19.99', 'Gurren Lagann', '0000-00-00', 2007, 'Hiroyuki Imaishi', 'Simon vit dans un petit village souterrain. Jour après jour, il fore le sol sans relâche et sans se poser de question, après tout, il n''est bon qu''à ça... Kamina, son grand frère spirituel, est un grand voyou casse-cou et arrogant qui rêve d''atteindre une "surface" dont il est le seul à croire en l''existence. \r\nPourtant un jour, suite à un terrible tremblement de terre le plafond du village s''effondre laissant apparaître le ciel. Un terrible robot descend alors dans le village et dit vouloir exterminer tous les habitants. Une fille du nom de Yoko, originaire du village voisin, débarque de nulle part bombardant l''ennemi et demande aux deux garçons de se mettre à l’abri... Ce que Kamina refuse de faire, décidant d''utiliser le dernier trésor que Simon à déterrer pour vaincre le robot : une espèce tête en métal. \r\n\r\nL''objet se révélant être doté de fabuleux pouvoirs, Kamina, Simon et Yoko parviennent à exploser le robot et s''échappent des sous-sols de la terre par la même occasion. Ce qu''ils découvrent à la surface est un monde dévasté dans lequel les êtres humains sont chassés tels du bétail par une autre race, les beastmen. Nos trois héros décident alors de former un groupe, la Gurren Brigade, pour mettre fin à l''oppression des beastmen et offrir ainsi à l''humanité une vie sous le soleil.', 'a_img_gurren.png', 2),
(11, '19.99', 'Ranma 1/2', '0000-00-00', 1987, 'Rumiko Takahashi', 'Effervescence chez la famille Tendô. Aujourd''hui doivent venir Genma Saotome et son fils Ranma, amis de la famille. Ranma est supposé épouser une des trois filles Tendô, tandis que le couple doit poursuivre l''exploitation du dojo familial Tendô. \r\n\r\nTout irait pour le mieux si M. Saotome ne passait pas sa vie sous forme d''un panda, et que Ranma Saotome n''alternait pas entre les formes d''un gentil lycéen ultra doué en arts martiaux et d''une ravissante jeune fille, dotée de presque autant de force physique que sa version homme, par la suite d''une baignade dans les sources maléfiques de Chine lors de son entraînement. Ranma a une peur bleue des chats et quand Shampoo, une de ses nombreuse fiancées, se transforme en chatte, il est paralysé de peur et ne peut s''en approcher. Ranma est devenu très fort en arts martiaux grâce à Genma qui lui a tout appris. \r\n\r\nLes héros évoluent dans un contexte de rivalité lycéenne autour de la beauté et de la force (avec comme prétexte et toile de fond les arts martiaux les plus délirants), et de découverte de l''amour par des jeunes ; outre la force et la compétition, les questions d''honneur et de respect des traditions jouent un rôle primordial. \r\n\r\nLa double apparence de Ranma, ainsi que les autres transformations humain/animal de plusieurs autres protagonistes (Cf. infra) constituent la source de nombreux quiproquos et coups de théâtre, au gré des expositions à l''eau froide (transformation) ou chaude (retour à la normale) dans des moments d''intimité. Il en résulte suspense et effets comiques à un rythme effréné, d''autant que les transformations sont un secret honteux pour tous, connu d''un petit cercle d''intimes, qui peuvent en user comiquement (comme lorsque la sœur d''Akané, Nabiki vend des photos de Ranma-fille à Kunô, sans lui dire bien sûr qu''il s''agit de Ranma transformé... ).\r\n', 'a_img_ranma.png', 2),
(12, '19.99', 'Angel Beats', '0000-00-00', 2009, 'Jun Maeda', 'Dans le monde de l''au-delà, les anges se battent pour leur destin. Yuri, la leader du Shinda Sekai Sensen (SSS), décide de se rebeller contre le dieu qui leur donne une vie sans but. Tenshi, la présidente du conseil des élèves pour un monde après la mort, se bats contre les membres du SSS, en employant des pouvoirs surnaturels, alors que les SSS emploie des armes technologiques.', 'a_img_angel.png', 2),
(13, '19.99', 'RahXephon', '0000-00-00', 2002, 'Yutaka Izubuchi', 'Ayato Kamina est abordé par le gouvernement de Mû qui le met en contact avec le Rah-xephon, un robot vivant qui attend son pilote, c''est à dire, Ayato. Cependant, un imprévu survient avec l''intervention de Reika Mishima, une mystérieuse camarade de classe, qui le pousse à s''enfuir avec le Rahxephon. Ayato rejoint le camps adverse, l''alliance terrestre, et se charge d''affronter Mû. Il est guidé par Haruka Shitow, une jeune femme, officier de renseignements chez Terra.', 'a_img_rah.png', 2),
(14, '19.99', 'Death Note', '0000-00-00', 2003, 'Tsugumi Oba', 'Yagami Light (Raito), un jeune étudiant surdoué, ramasse un jour le "Death Note", un carnet tenu auparavant par un Shinigami, Ryuk (Ryuuku), qui apparemment s''ennuyait dans son monde.\r\nIl suffit d''écrire le nom d''une personne dans ce carnet et celle-ci meurt (selon certaines conditions que le Shinigami expliquera à Light lors de leur rencontre).\r\nC''est ainsi qu''avec le "Death Note" entre les mains, Light décide de débarrasser la planète de tous les criminels pour en faire un monde juste, un monde parfait.\r\nCependant, qui est-il pour juger les gens? \r\nIl devient du même coup le pire criminel recherché de toute la planète...', 'a_img_death.png', 2),
(15, '19.99', 'Nicky Larson', '0000-00-00', 1987, 'Kenji Kodama', 'Ryô Saeba, alias Cityhunter, est un nettoyeur professionnel (un tueur à gages). Ses spécialités reposent dans l''investigation et le travail de garde du corps. Dans le milieu, il est le meilleur. Son habileté et sa précision dans le tir font de lui le tueur le plus redouté.\r\n\r\nLa série commence avant la mort de son partenaire Hideyuki Makimura, assassiné par l''Union Teope, grande organisation criminelle. Ce puissant groupe travaillant dans la drogue en Amérique du Sud cherche à s''implanter au Japon et contacte City Hunter pour qu''il protège le réseau. Devant leur refus, l''Union Teope décide d''éliminer ces témoins gênants et dangereux. \r\nAprès avoir vengé son ami, il demande à Kaori de s''échapper car l''Union Teope en a après elle. Kaori refuse de s''échapper. Elle veut rester auprès de Ryô pour remplacer son frère et régler ses comptes.', 'a_img_nicky.png', 2),
(16, '19.99', 'Darker than Black', '0000-00-00', 2007, 'Tensai Okamura', 'Un étrange champ de force d''origine inconnue s''est dressé autour de Tokyo il y a dix ans. On l''appelle "la porte des enfers" (Hell''s gate). La police découvre l''existence d''êtres surnaturels la semaine qui suit la création, les Contractors, êtres d''apparence humaine possédant des pouvoirs surhumains, et les Dolls, êtres générés par un programme. Pour n''éveiller aucune panique de la part des habitants de Tokyo, une section, la "quatrième section des Affaires Étrangères", dont fait partie l''agent Kirihara Misaki, s''occupe d''effacer la mémoire de tout habitant entrant en contact avec un Contractor. Une scientifique du nom de Shinoda Chiaki ayant fait une thèse à propos de la porte se voit être poursuivie par la police dans l''optique de lui effacer sa mémoire. Elle rencontre alors Li, un chinois qui vient d''emménager à Tokyo, qui la protège des Contractors et de la police. Cet homme semble avoir des liens irrémédiables avec un homme mystérieux vouant une haine, plus sombre que le noir, aux Contractor.', 'a_img_darker.png', 2),
(17, '19.99', 'Ghost in the Shell', '0000-00-00', 1989, 'Masamune Shirow', 'Ghost in the Shell est un thriller policier futuriste racontant les exploits de la cyborg Motoko Kusanagi, membre d''une division des opérations clandestines de la Japanese National Public Safety Commission connue sous le nom de Section 9, l''unité spécialisée dans la lutte contre les crimes liés à la technologie. \r\nLe cadre de Ghost in the Shell est cyberpunk ou postcyberpunk, semblable à celui de la trilogie de William Gibson. Kusanagi et ses collègues sont confrontés à des menaces extérieures et aussi touchés par un conflit interne à l''égard de leurs propres natures...\r\n', 'a_img_ghost.png', 2),
(18, '19.99', 'One Piece', '0000-00-00', 1997, 'Eiichiro Oda', 'Il fut un temps ou Gold Roger était le plus grand de tous les pirates, le "Roi des Pirates" était son surnom. A sa mort, son trésor d''une valeur inestimable connu sous le nom de "One Piece" fut caché quelque part dans la "Grand Line". De nombreux pirates sont partis à la recherche de ce trésor mais tous sont morts avant même d''atteindre la "Grand Line" ! Monkey D. Luffy rêve de retrouver ce trésor légendaire et de devenir le nouveau "Roi des Pirates". Après avoir mangé un fruit du démon, il possède un pouvoir lui permettant de réaliser son rêve. Il lui faut maintenant trouver un équipage pour partir à l''aventure !', 'a_img_piece.png', 2),
(19, '19.99', 'Hunter X Hunter', '0000-00-00', 2011, 'Yoshihiro Togashi', 'Gon Freeks est un jeune garçon provenant d''un petit village aimé des animaux. Il rêve de devenir Hunter afin de retrouver son père, le plus grand Hunter de tous, qu''il n''a jamais vu qu''en photo. Mais pour devenir Hunter professionnel, il faut passer plusieurs épreuves et tests très difficiles. Pendant les épreuves, Gon fait la connaissance d''amis tel que Kirua, Kurapica, Leorio mais de très dangereux combattants sont également présent afin de passer le test de Hunter.', 'm_img_hxh.png', 1),
(20, '19.99', 'Fairy Tail', '0000-00-00', 2011, 'Hiro Mashima', 'Lucy est une jeune magicienne qui désire plus que tout entrer dans une guilde magique.\r\nElle décide de se rendre à Harujion afin d''obtenir des infos sur des guildes, particulièrement la guilde Fairy Tail.\r\n\r\nLors de ses recherches, elle rencontre le mystérieux Salamander membre de la célèbre Guilde Fairy Tail.\r\nMalheureusement ce dernier n''est qu''un charlatan qui utilise des enchantements pour envoûter des femmes pour ensuite les revendre au marché des esclaves !\r\n\r\nAlors que Lucy se trouve sous l''envoûtement de Salamander, un garçon mystérieux du nom de Natsu accompagné d''un chat bleu pouvant parler appelé Happy, la percute et rompt le sortilège de Salamander. Pour remercier Natsu et Happy elle décide de les invités au restaurant. Plus tard, Salamander lui fit une proposition " Si elle viens à la fête sur le bateau (organisé par Salamander) il la ferait entrer a Fairy Tail". Lucy accepte et s''y rend. A la fête elle se rend compte que Salamander n''est qu''un escroc et qu''il ne fait même pas partie de Fairy Tail, elle veut fuir mais elle est sur le point de se faire kidnapper lorsque Natsu et Happy arrive et sauve Lucy, c''est alors quel découvre qu''ils sont des mages et qu''ils font partie de Fairy Tail.\r\n\r\nC''est le début des aventures de Natsu et Lucy au sein du monde magique de Fairy Tail !', 'm_img_ft.png', 1),
(21, '19.99', 'Naruto', '0000-00-00', 2011, 'blabla', 'Dans le village de Konoha vie Naruto, un jeune garçon détesté et craint des villageois. Il est craint du faite qu''il détient en lui Kyuubi (démon renard à neuf queues) d''une incroyable force, qui a tué un grand nombre de personnes. Le ninja le plus puissant de Konoha à l''époque, le quatrième Hokage, Yondaime réussit à sceller ce démon dans le corps de Naruto.\r\nMalheureusement il y laissa la vie.\r\n\r\nC''est ainsi que douze ans plus tard, Naruto rêve de devenir le plus grand Hokage de Konoha afin que tous le reconnaissent. Mais la route pour devenir Hokage est très longue et Naruto doit remplir un bon nombre d''épreuves et affronter de nombreux ennemis pour atteindre son but !', 'm_img_naruto.png', 1),
(22, '19.99', 'Elfen Lied', '0000-00-00', 2011, 'Lynn Okamoto', 'Lucy, une diclonius (génération spontanée de mutants annonçant un événement), est gardée dans un laboratoire de haute sécurité dans lequel des expériences sont réalisées sur ces êtres surhumains. Suite à un accident, elle parvient à s''échapper en tuant sauvagement toute personne entravant son chemin, grâce à ses "main" (ce sont des "mains" extrêmement tranchantes, personne ne les voient). Une fois à l''extérieur du bâtiment, un garde sniper réussit à la toucher en pleine tête et la fait tomber dans la mer.\r\n\r\nLe lendemain, Kouta un jeune garçon qui revient dans la ville où il est né, Kamakura, donne un rendez-vous à sa cousine Yuka qu''il n''a pas vu depuis son accident : depuis son enfance. Ils décident alors d''aller à la plage, où ils jouaient quand ils étaient enfants avec la petite soeur de Kouta, Kanae, qui est morte d''une grave maladie. Là-bas, ils rencontrent une jeune fille mystérieuse qui, apparemment, a perdu la mémoire. Sans savoir où elle habite, Kouta et Yuka l''emmènent chez eux et lui donne un nom : Nyu, c''est le seul mot qu''elle arrive a prononcer !\r\n\r\nMais suite à l''évasion qui s''est produite au laboratoire, l''Unité d''Assaut Spécial (S.A.T.) a reçu le feu vert pour éliminer la fugitive, Lucy qui se révèle en réalité être la mystérieuse Nyu...', 'm_img_elfen.png', 1),
(23, '19.99', 'Gantz', '0000-00-00', 2000, 'Hiroya Oku', 'Tout se passe dans une station de métro, Kei Kurono, un étudiant typique qui ne se préoccupe que de lui-même, attend tranquillement le métro pour rentre chez lui. Soudain, un clochard ayant un peu trop bu s''évanouit et tombe sur les rails. Personne ne vient lui porter secours mis à part Masaru Katô, un ami d''enfance de Kei. Il demande à Kei de l''aider mais quand ils réussissent à remonter le clochard, il est trop tard. Le métro arrive et ne leur laisse pas le temps de regagner le quai. Ils sont écrasés. Quelques secondes plus tard, ils se retrouvent téléportés dans un appartement fermé en compagnie de d''autres personnes récemment tuées. A partir de maintenant leur vie va être contrôlée par une mystérieuse boule noire appelée GANTZ et seront forcés de participer à un "jeu" de danger et d''horreur sans précédent.', 'm_img_gantz.png', 1),
(24, '19.99', 'School Rumble', '0000-00-00', 2003, 'Jin Kobayashi', 'Tenma Tsukamoto, une lycéenne un peu idiote, est folle amoureuse de Ouji Karasuma, un garçon de son lycée. Elle se retrouve dans la même classe que lui et espère bien pouvoir lui déclarer sa flamme. Parallèlement à cela, Kenji Harima un lycéen voyou très bagarreur est lui amoureux de Tsukamoto, mais ne sait pas comment lui avouer ses sentiments.\r\nCes trois-là se retrouvent dans la même classe. Tsukamoto et Harima vont tout faire pour\r\nséduire l''élu de leur coeur et il va en découler une vraie série de gags.', 'm_img_rumble.png', 1),
(25, '19.99', 'Special A', '0000-00-00', 2003, 'Minami Maki', 'Kei Takishima a toujours été meilleur que Hikari Hanazono, le personnage principal. Alors que Hikari considère Kei comme son plus grand rival et une sorte d''ami, Kei aime Hikari. Tout le monde le sait, à part elle qui est trop obnubilée par son obsession : battre Kei dans n''importe quel domaine. Kei & Hikari se connaissent depuis qu''ils ont six ans grâce à leurs pères, tous deux amateurs de catch. Pensant qu''elle était la meilleure à ce sport, Hikari a défié Kei, défi qu''elle a perdu. Depuis ce fatidique incident, Hikari a juré de battre Kei dans n''importe quel domaine, que ce soit à l''école ou encore à une compétition de sport. Pour cela, Hikari s''est arrangée pour se trouver dans le même établissement scolaire et la même classe que Kei depuis l''école élémentaire. Maintenant, elle a intégré la Hakusenkan, une université d''élite très réputée, ce qui a demandé beaucoup d''argent à son père, simple carpentier. Hikari et Kei sont les deux meilleurs élèves de cette école où Kei reste sans mal à la première place.\r\nHikari va t-elle surpasser son rival ou réaliser qu''il l''aime?', 'm_img_special.png', 1),
(26, '19.99', 'Rave', '0000-00-00', 1999, 'Hiro Mashima', 'Il y a une cinquantaine d''années, deux royaumes se déchiraient dans une guerre : le royaume de Symphonia et celui de Rareglobe. Chacun possédait une pierre aux dangereux pouvoirs : Symphonia possédait Rave et Rareglobe possédait les Dark Bring. La guerre prit fin à la suite d''un gigantesque cataclysme qui détruisit les deux cités.\r\n\r\nCinquante ans plus tard, Shiba, le Rave Master atteint une petite île où il trouve enfin son héritier en la personne de Haru, un adolescent de l''île. Il lui confie Rave, et lui donne pour mission de réunir les 4 fragments manquant, avant que Demon Card, une organisation criminelle, ne réunisse les Dark Bring qu''ils ont éveillés.', 'm_img_rave.png', 1),
(27, '19.99', 'Tokyo Ghoul', '0000-00-00', 2014, 'Shuhei Morita', 'L''histoire se déroule dans un Tokyo moderne mais hanté par de mystérieuses "goules" dévorant les humains. La peur et le chaos règnent sur la ville mais certaines personnes tentent malgré tout d''avoir une vie "normale".\r\nC''est notamment le cas de Ken Kaneki, un étudiant de 18 ans. Mais, un jour, il est attaqué par une goule et manque d''y laisser sa peau. Sauvé de justesse, il survit grâce aux organes de la goule, greffés à la place de ceux qu''elle avait détruit en l''attaquant. Le jeune homme est désormais un hybride et va vivre un véritable enfer .', 'm_img_ghoul.png', 1),
(28, '19.99', 'Mobile Suit Gundam Seed', '0000-00-00', 2002, 'Mitsuo Fukuda', 'Les humains se sont lancés dans la conquête de l''espace avec le développement des technologies. Ils ont créé de gigantesques colonies spatiales regroupant des villes entières. Ceux qui ont amorcé le développement de ces vastes chantiers sont les Coordinators, des êtres "supérieurs" ayant subis des modifications génétiques. Ils proclament leur indépendance par rapport à l''alliance terrestre et créer leur propre gouvernement : Zaft. Hélas, les tensions entre les Narutels (personne n''ayant subit aucune modification génétique) et les Coordinators se font ressentir et un conflit militaire explose entre l''alliance terrestre et les colonies rebelles telle que PLANT. L''alliance terrestre lance alors une bombe thermonucléaire sur la colonie civile, Junius 7, causant la mort de centaine de millier de personnes.\r\n\r\nAn 70 de l''ère cosmique. Cela fait presque 11 mois que la guerre a débuté et il n''y a pour l''instant aucun signe de fin. La colonie spatiale neutre d''Héliopolis suit les informations de loin. Kira Yamato, un coordinateur y vit paisiblement avec ses amis. Soudain, la colonie se fait attaquer par Zaft qui tente d''empêcher le transfert de quatre mobiles suit Gundam. Kira se retrouve alors impliqué malgré lui dans le combat...', 'm_img_gundam.png', 1),
(29, '19.99', 'Détective Conan', '0000-00-00', 1994, 'Gosho Aoyama', 'Shinichi Kudo est un brillant lycéen promis à un grand avenir. Il vit seul car ses parent vivent aux États-Unis, mais il passe beaucoup de temps avec Ran, son amie d''enfance, ou avec le professeur Agasa. C''est un excellent détective, qui a le sens de l''observation et un très bon esprit de déduction, mais un jour, il va se faire surprendre alors qu''il espionnait deux hommes en noir suspects. Ils lui feront alors prendre un médicament sensé le tuer, mais qui va le faire rajeunir et il redeviendra un gamin de 6 ans. Coincé dans ce corps d''enfant, Shinichi se fera alors passer pour Conan Edogawa, neveu du professeur, et se fera "adopter" par Ran dont le père est détective privé. Conan espère ainsi retrouver les hommes en noir, et enfin redevenir lui même.', 'a_img_conan.png', 2),
(30, '19.99', 'Bus Gamer', '0000-00-00', 1999, 'Kazuya Minekura', 'Trois jeunes hommes que tout semble opposer, Kazuo Saito, Nobuto Nakajyo et Toki Mishiba reçoivent une mystérieuse enveloppe noire contenant une invitation pour participer à un jeux... dangereux.\r\nCes trois dernier vont y répondre et seront sélectionnés, contraints de faire équipe ensemble sous le nom de AAA (signifiant "no name").\r\nIl se trouve que le but de ce jeu est de récupérer ou protéger une disquette, pour le moins intrigante. Malgré la difficulté au fur et à mesure des "parties", nos jeunes ne se dégonflent pas, bien décidés à gagner et à atteindre leur but commun...', 'm_img_bus.png', 1),
(31, '19.99', 'Kenshin le vagabond', '0000-00-00', 1994, 'Nobuhiro Watsuki', 'Au milieu du siècle dernier, le Japon s''apprête à entrer dans l''ère Meiji, passant sans transition du Moyen Age à l''industrialisation. Les samouraïs n''ont plus leur place dans cette société moderne où les guerriers sont moins utiles que les commerçants. Sans emploi, n''ayant plus le droit de porter le sabre, confrontés aux fusils et aux canons, les samouraïs vont peu à peu disparaître pour entrer dans la légende.\r\n\r\nKenshin est l''un de ces guerriers perdus. Grand maître de sabre il est devenu un vagabond errant sur les routes du Japon. Mais son esprit chevaleresque et son courage vont faire de cet ancien mercenaire un justicier aimé et respecté.', 'm_img_kenshin.png', 1),
(32, '19.99', 'Samourai Deeper Kyo', '0000-00-00', 1999, 'Akimine Kamijyo', 'Kyoshiro Mibu est un pharmacien ambulant recherché, ce qui attire une jeune femme du nom de Yuya Shiina, une jeune chasseuse de prime plutôt célèbre. Mais il s''avère que Kyoshiro abrite en lui le tueur aux 1000 victimes, le célèbre et meurtrier Kyo aux yeux de démon.\r\n\r\nCe dernier ne veut qu''une seule chose : récupérer son corps. Et pour cela il entreprendra une quête à travers tout le Japon, recontrant divers personnages comme Tigre Rouge ou encore Sanada Yukimura.\r\nYuya décide de suivre ce tueur car avec une prime de 1 million de Ryo sur sa personne il est hors de question de le laisser filer. Mais elle apprendra que Kyo et Kyoshiro sont liés d''une façon trouble et que ce dernier est loin d''être celui qu''elle pensait. Et lorsqu''enfin le Clan Mibu fait surface, elle s''apercoit que la réponse à ses questions n''est pas si facile à atteindre.', 'm_img_kyo.png', 1),
(33, '19.99', 'Pandora Hearts', '0000-00-00', 2006, 'Jun Mochizuki', 'Oz Vessalius, héritier d''une maison de Duc, vient tout juste d''avoir quinze ans. Sa vie est riche et insouciante, mais assombrie par l''absence constante de son père...\r\n\r\nLors de son passage à l''âge de la cérémonie, tout change. Pour aucune raison apparente, il est jeté dans la prison connue sous le nom de "Abyss", pour être sauvé par une "chain" connue sous le nom d''Alice, le lapin de sang noir. Pourquoi a t-il été jeté dans Abyss ? Qui est réellement Alice dans tout cela ? Qu''est ce que l''organisation connue sous le nom de "Pandora" lui veut ?', 'm_img_pandora.png', 1),
(34, '19.99', 'Vampire Knight', '0000-00-00', 2004, 'Matsuri Hino', 'Il y a maintenant quelques années, une jeune fille du nom de Yuki fut attaquée par un vampire... puis secourue par un autre.\r\nUne dizaine d''années après, la fille adoptive du dirigeant de l''Académie CROSS, Yuki Cross, est devenue une gardienne de la race des vampires. Elle protège Kuran Kaname, son salvateur, du monde des humains.\r\nCependant, Zero KIRYU, son meilleur ami, est conscient de l''existence des vampires. Il les hais plus que tout car ils ont massacré tous ceux qui étaient chère à son cœur. Yuki commence alors à se poser des questions quant à la vraie nature de ces vampires qui ont décimé la famille de son meilleur ami :\r\nSont-ils réellement bons ? Représentent-ils un danger quelconque ? L''amour qu''elle se met à ressentir envers Kaname serait-il un amour interdit ?', 'm_img_vampire.png', 1),
(35, '19.99', 'Lucky Star', '0000-00-00', 2004, 'Kagami Yoshimizu', 'Lucky Star s''intéresse aux vies de plusieurs jeunes lycèennes japonaises, donnant une touche d''humour à leurs histoires. L''héroïne principale est Konata Izumi, une jeune fille sportive et intelligente qui, malgré ces qualités, ne fait pas partie d''un club sportif et a de mauvaises notes. Sa paresse face au travail à l''école s''explique par son amour pour l''anime et les jeux vidéo au détriment de tout le reste. Le feuilleton commença avec la première année de lycée des quatre personnages principaux : Konata Izumi, Kagami Hiiragi, Tsukasa Hiiragi, et Miyuki Takara. L''intrigue avance, les filles progressant à leurs deuxième et troisième années lycéennes.', 'm_img_lucky.png', 1),
(36, '19.99', 'Ixion Saga DT', '0000-00-00', 2012, 'Shinji Takamatsu', 'Kon, un adolescent tout à fait normal, va, un jour, se retrouver dans un monde alternatif alors qu''il accepte la requête d''une mystérieuse jeune fille dans un jeu en ligne. C''est ainsi qu''après avoir sauvé, bien malgré lui, la princesse Ecarlate, il se retrouve à voyager avec elle et ses deux compagnons : le chevalier Sainglain et l''étrange dame de compagnie Mariandel. Ensemble, ils doivent rejoindre la capitale : la princesse pour s''y marier et Kon pour y trouver un moyen de retourner dans son monde. Malheureusement, une faction adversaire, avec à ses commandes Erecpyle Dukakis, ne souhaitant pas voir aboutir ce projet, va tout faire pour empêcher le groupe d''atteindre son but...', 'm_img_ixion.png', 1),
(37, '19.99', 'Sword art Online', '0000-00-00', 2012, 'Reki Kawahara', 'Cette série raconte les aventures de Kirito qui se retrouve piégé dans un jeu massivement multi-joueurs, Sword Art Online.\r\n\r\nEn 2022, l’humanité a réussi à créer une réalité virtuelle. Grâce à un casque, les humains peuvent se plonger entièrement dans le monde virtuel en étant comme déconnectés de la réalité, et Sword Art Online est le premier MMORPG a utiliser ce système. Mais voila que le premier jour de jeu, 10 000 personnes se retrouvent piégées dans cette réalité virtuelle par son créateur : Akihiko Kayaba. Le seul moyen d’en sortir est de finir le jeu. Mais ce ne sera pas facile de sortir de ce monde virtuel puisque si un joueur perd la partie, il meurt également dans la vraie vie.\r\n\r\nKirito décide alors de partir à la conquête du jeu en solo, avec pour avantage le fait de faire partie des 1 000 ex-bêta-testeurs, mais arrivera-t-il à terminer les 99 donjons et leurs boss ?\r\n\r\n"Même si cela semble être un jeu vidéo, ce n''est pas un jeu"\r\nAkihiko Kayaba - Développeur de "Sword Art Oline"', 'l_img_sao.png', 3),
(38, '19.99', 'Mahouka Koukou no Rettousei', '0000-00-00', 2012, 'Tsutomu Satou', 'La "Magie" que nous connaissons n''est issue ni des légendes, ni des contes de fées. Elle est devenue une réelle technologie depuis près d''un siècle. Plusieurs pays de ce monde s''opposent dans une course à la formation de "Magiciens". Tatsuya Shiba est un étudiant sans capacités magiques inscrit au Premier Lycée de Magie ;il y étudie avec sa soeur Miyuki, qui se trouve être la meilleure élève parmi les première années.', 'l_img_mkr.png', 3),
(39, '19.99', 'All You Need Is Kill', '0000-00-00', 2012, 'Hiroshi Sakurazaka', 'Keiji Kiriya, nouvelle recrue de l’armée de Défense des Etats, a pour but de détruire de terribles aliens, appelés Mimics (les imitateurs). \r\n\r\nAu cours de sa première bataille, il est vite tué au combat face à ces dangereux envahisseurs.\r\nCependant, inexplicablement, et à sa grande surprise, il se réveille la veille de son décès. Il finit rapidement par comprendre qu’il est coincé dans une boucle temporelle, lui faisant revivre sa mort et sa résurrection !\r\nKeiji va donc chercher le moyens de se sortir de cette boucle et sa rencontre avec Rita Vrataskin, soldat coriace, va lui redonner espoir...', 'l_img_aynik.png', 3),
(40, '19.99', 'Fate/Zero', '0000-00-00', 2012, 'Gen Urobuchi', 'Les événements de Fate/Zero se passent 10 ans avant l''histoire de Fate/Stay Night.\r\n\r\nIl y a de cela plusieurs siècles, trois grandes familles de mages nommées Einzbern, Tohsaka et Matô, s''allièrent pour invoquer le Saint Graal, relique pouvant accorder n''importe quel vœux. Mais les familles découvrirent qu''un seul individu pourrait en profiter et elles décidèrent donc de briser leur alliance.\r\n\r\nAujourd''hui, la quatrième guerre est sur le point de débuter dans la ville de Fuyuki, après 60 ans de trêve. Kiritsugu Emiya, au service de la famille Einzbern, invoque le servant de classe Saber.\r\nAidés de Irisviel von Einzbern, il va se battre contre les six autres servants et leurs maîtres, pour tenter d''obtenir le premier la relique sacrée et maintenir la paix.', 'l_img_fatezero.png', 3),
(41, '19.99', 'Log Horizon', '0000-00-00', 2012, 'Mamare Touno', 'Shiroe est amateur de MMORPG. Un jour, alors qu''il joue à Elder Tales, il se retrouve piégé dans le jeu avec 30 000 autres personnes. Désormais, impossible d''utiliser le bouton de log out ou de se faire tuer.\r\n\r\nPeu à peu, les joueurs perdent la volonté de jouer, comprenant qu''ils y finiront leur vie. Mais Shiroe ne veut pas abandonner. Il débute alors un voyage afin de comprendre d''où vient le problème.', 'l_img_loghorizon.png', 3),
(42, '19.99', 'Tokyo Ravens', '0000-00-00', 2012, 'Kōhei Azano', 'Tsuchimikado Harutora fait partie d''une prestigieuse famille d''Onmyoji (spécialistes en magie et en divination) mais il ne parvient pas à voir l''énergie spirituelle.\r\n\r\nC''est donc un lycéen ordinaire jusqu''au jour où son amie d''enfance, Tsuchimikado Natsume, l''héritière de la famille, apparaît.\r\n\r\nL''arrivée de celle-ci va faire basculer sa vie.', 'l_img_tokyoravens.png', 3),
(43, '19.99', 'No Game No Life', '0000-00-00', 2012, 'Kamiya Yuu', 'Sora et Shiro sont deux frère et soeur hikikomori. L''hikikomori désigne une pathologie psycho-sociale caractérisant les personnes (souvent des adolescents) qui vivent coupées du monde en restant cloîtré chez eux, refusant toute communication. Dans le cas des deux protagonistes, leur condition vient de leur vision du monde réel, qui se résume à un jeu merdique.\r\n\r\nEnsemble, ils forment un duo de joueurs invaincus, véritable légende urbaine. Un jour, un garçon se qualifiant de "Dieu" les appelle dans un monde fantastique, où il a interdit toute forme de violence entre les 16 races différentes y vivant. A la place, toute décision ou conflit est réglé par le jeu. Les deux adolescents y sont convoqués car ils pourraient bien être les sauveurs de l''humanité, la race Imanity qui, classée dernière parmi les 16 races, se retrouve confinée dans leur seule et unique cité restante.', 'l_img_ngnl.png', 3),
(44, '19.99', 'Chrome Shelled Regios', '0000-00-00', 2012, 'Shūsuke Amagi', '"Kōkaku no Regios" se situe dans un monde pollué et dans lequel des créatures appelées "Limbeekoon" térrorisent l''humanité.\r\n\r\nUn jeune homme se nommant Layfon Alseif s''inscrit en tant qu''étudiant de rang D dans une des villes mobiles isolées (appelée Regios), la ville Académie de Zenri. Peu après son arrivée, il se fait remarquer en arrêtant un combat entre deux étudiants des Arts Militaires par Nina Antalk, chef de la 17ème Unité d''Arts Militaire. Layfon se fait intégrer dans l''Unité à l''aide du Président du Conseil des étudiant Karian Loss.\r\n\r\nQue va-t-il arriver par la suite? Qui sait? ...', 'l_img_csr.png', 3),
(45, '19.99', 'Hunter X Hunter    The Last Mission', '0000-00-00', 2011, 'Yoshihiro Togashi', 'Autrefois, les Hunters les plus forts ont été divisés en deux. Un côté Lumière et un côté Ténèbres. Chacun emprunta une voie différente.\r\n\r\nPlusieurs années plus tard, le côté des Ténèbres ressurgit et attaque Kirua et Kurapika. Ils ont la ferme intention d''exterminer tous les Hunters encore en activité.\r\nCe groupe est mené par un certain Jed, un individu qui semble étroitement lié à Netero, le président de l''association des Hunters.\r\n\r\nAinsi commence une véritable guerre opposant les Hunters à leur côté sombre...', 'f_img_hxh_tlm.png', 4),
(46, '19.99', 'Hunter X Hunter    Phantom Rouge', '0000-00-00', 2011, 'Yoshihiro Togashi', 'L''histoire se passe juste après l''arc de York Shin City.\r\n\r\nKurapika est devenu Hunter de la Black List pour se venger de la Brigade Fantôme, une organisation à l’origine du massacre de son clan.\r\n\r\nEn effet, les yeux des membres du clan Kuruta deviennent écarlates lors de fortes émotions et se vendent extrêmement chers au marché noir. Malgré l’intervention de Gon, Kirua et Leolio, Kurapika se fait voler ses yeux par un ancien membre du clan Kuruta !\r\n\r\nAinsi commence le combat contre la Brigade Fantôme, la véritable identité du N°4 et la révélation du passé de Kurapika.', 'f_img_hxh_pr.png', 4);

--
-- Index pour les tables exportées
--

--
-- Index pour la table `item`
--
ALTER TABLE `item`
 ADD PRIMARY KEY (`item_id`), ADD KEY `fk_item_item_type` (`item_type_id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `item`
--
ALTER TABLE `item`
MODIFY `item_id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=47;
--
-- Contraintes pour les tables exportées
--

--
-- Contraintes pour la table `item`
--
ALTER TABLE `item`
ADD CONSTRAINT `fk_item_item_type` FOREIGN KEY (`item_type_id`) REFERENCES `item_type` (`item_type_id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
